# CMake generated Testfile for 
# Source directory: /home/cc/local_build/zfp/tests/src/encode
# Build directory: /home/cc/local_build/zfp/build_debug/tests/src/encode
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testZfpEncodeBlock1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock1dInt32")
add_test(testZfpEncodeBlockStrided1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided1dInt32")
add_test(testZfpEncodeBlock1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock1dInt64")
add_test(testZfpEncodeBlockStrided1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided1dInt64")
add_test(testZfpEncodeBlock2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock2dInt32")
add_test(testZfpEncodeBlockStrided2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided2dInt32")
add_test(testZfpEncodeBlock2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock2dInt64")
add_test(testZfpEncodeBlockStrided2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided2dInt64")
add_test(testZfpEncodeBlock3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock3dInt32")
add_test(testZfpEncodeBlockStrided3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided3dInt32")
add_test(testZfpEncodeBlock3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock3dInt64")
add_test(testZfpEncodeBlockStrided3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided3dInt64")
add_test(testZfpEncodeBlock4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock4dInt32")
add_test(testZfpEncodeBlockStrided4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided4dInt32")
add_test(testZfpEncodeBlock4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock4dInt64")
add_test(testZfpEncodeBlockStrided4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided4dInt64")
add_test(testZfpEncodeBlock1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock1dFloat")
add_test(testZfpEncodeBlockStrided1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided1dFloat")
add_test(testZfpEncodeBlock1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock1dDouble")
add_test(testZfpEncodeBlockStrided1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided1dDouble")
add_test(testZfpEncodeBlock2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock2dFloat")
add_test(testZfpEncodeBlockStrided2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided2dFloat")
add_test(testZfpEncodeBlock2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock2dDouble")
add_test(testZfpEncodeBlockStrided2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided2dDouble")
add_test(testZfpEncodeBlock3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock3dFloat")
add_test(testZfpEncodeBlockStrided3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided3dFloat")
add_test(testZfpEncodeBlock3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock3dDouble")
add_test(testZfpEncodeBlockStrided3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided3dDouble")
add_test(testZfpEncodeBlock4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock4dFloat")
add_test(testZfpEncodeBlockStrided4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided4dFloat")
add_test(testZfpEncodeBlock4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlock4dDouble")
add_test(testZfpEncodeBlockStrided4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpEncodeBlockStrided4dDouble")
