# CMake generated Testfile for 
# Source directory: /home/cc/local_build/zfp/tests/src/endtoend
# Build directory: /home/cc/local_build/zfp/build_debug/tests/src/endtoend
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testZfpSerial1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial1dInt32")
add_test(testZfpOmp1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp1dInt32")
set_tests_properties(testZfpOmp1dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda1dInt32")
set_tests_properties(testZfpCuda1dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial1dInt64")
add_test(testZfpOmp1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp1dInt64")
set_tests_properties(testZfpOmp1dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda1dInt64")
set_tests_properties(testZfpCuda1dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial2dInt32")
add_test(testZfpOmp2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp2dInt32")
set_tests_properties(testZfpOmp2dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda2dInt32")
set_tests_properties(testZfpCuda2dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial2dInt64")
add_test(testZfpOmp2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp2dInt64")
set_tests_properties(testZfpOmp2dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda2dInt64")
set_tests_properties(testZfpCuda2dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial3dInt32")
add_test(testZfpOmp3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp3dInt32")
set_tests_properties(testZfpOmp3dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda3dInt32")
set_tests_properties(testZfpCuda3dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial3dInt64")
add_test(testZfpOmp3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp3dInt64")
set_tests_properties(testZfpOmp3dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda3dInt64")
set_tests_properties(testZfpCuda3dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial4dInt32")
add_test(testZfpOmp4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp4dInt32")
set_tests_properties(testZfpOmp4dInt32 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial4dInt64")
add_test(testZfpOmp4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp4dInt64")
set_tests_properties(testZfpOmp4dInt64 PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial1dFloat")
add_test(testZfpOmp1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp1dFloat")
set_tests_properties(testZfpOmp1dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda1dFloat")
set_tests_properties(testZfpCuda1dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial1dDouble")
add_test(testZfpOmp1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp1dDouble")
set_tests_properties(testZfpOmp1dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda1dDouble")
set_tests_properties(testZfpCuda1dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial2dFloat")
add_test(testZfpOmp2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp2dFloat")
set_tests_properties(testZfpOmp2dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda2dFloat")
set_tests_properties(testZfpCuda2dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial2dDouble")
add_test(testZfpOmp2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp2dDouble")
set_tests_properties(testZfpOmp2dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda2dDouble")
set_tests_properties(testZfpCuda2dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial3dFloat")
add_test(testZfpOmp3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp3dFloat")
set_tests_properties(testZfpOmp3dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda3dFloat")
set_tests_properties(testZfpCuda3dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial3dDouble")
add_test(testZfpOmp3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp3dDouble")
set_tests_properties(testZfpOmp3dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpCuda3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpCuda3dDouble")
set_tests_properties(testZfpCuda3dDouble PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial4dFloat")
add_test(testZfpOmp4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp4dFloat")
set_tests_properties(testZfpOmp4dFloat PROPERTIES  RUN_SERIAL "TRUE")
add_test(testZfpSerial4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpSerial4dDouble")
add_test(testZfpOmp4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpOmp4dDouble")
set_tests_properties(testZfpOmp4dDouble PROPERTIES  RUN_SERIAL "TRUE")
