# CMake generated Testfile for 
# Source directory: /home/ubuntu/local_build/zfp/tests/array
# Build directory: /home/ubuntu/local_build/zfp/build_debug/tests/array
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testArray1f "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1f")
add_test(testArray1fRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1fRefs")
add_test(testArray1fPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1fPtrs")
add_test(testArray1fIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1fIters")
add_test(testArray1fViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1fViews")
add_test(testArray2f "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2f")
add_test(testArray2fRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2fRefs")
add_test(testArray2fPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2fPtrs")
add_test(testArray2fIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2fIters")
add_test(testArray2fViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2fViews")
add_test(testArray3f "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3f")
add_test(testArray3fRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3fRefs")
add_test(testArray3fPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3fPtrs")
add_test(testArray3fIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3fIters")
add_test(testArray3fViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3fViews")
add_test(testArray1d "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1d")
add_test(testArray1dRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1dRefs")
add_test(testArray1dPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1dPtrs")
add_test(testArray1dIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1dIters")
add_test(testArray1dViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray1dViews")
add_test(testArray2d "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2d")
add_test(testArray2dRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2dRefs")
add_test(testArray2dPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2dPtrs")
add_test(testArray2dIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2dIters")
add_test(testArray2dViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray2dViews")
add_test(testArray3d "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3d")
add_test(testArray3dRefs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3dRefs")
add_test(testArray3dPtrs "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3dPtrs")
add_test(testArray3dIters "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3dIters")
add_test(testArray3dViews "/home/ubuntu/local_build/zfp/build_debug/bin/testArray3dViews")
add_test(testConstruct "/home/ubuntu/local_build/zfp/build_debug/bin/testConstruct")
subdirs(zfp)
