# CMake generated Testfile for 
# Source directory: /home/cc/local_build/zfp/tests/src/decode
# Build directory: /home/cc/local_build/zfp/build_debug/tests/src/decode
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testZfpDecodeBlock1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock1dInt32")
add_test(testZfpDecodeBlockStrided1dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided1dInt32")
add_test(testZfpDecodeBlock1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock1dInt64")
add_test(testZfpDecodeBlockStrided1dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided1dInt64")
add_test(testZfpDecodeBlock2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock2dInt32")
add_test(testZfpDecodeBlockStrided2dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided2dInt32")
add_test(testZfpDecodeBlock2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock2dInt64")
add_test(testZfpDecodeBlockStrided2dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided2dInt64")
add_test(testZfpDecodeBlock3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock3dInt32")
add_test(testZfpDecodeBlockStrided3dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided3dInt32")
add_test(testZfpDecodeBlock3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock3dInt64")
add_test(testZfpDecodeBlockStrided3dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided3dInt64")
add_test(testZfpDecodeBlock4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock4dInt32")
add_test(testZfpDecodeBlockStrided4dInt32 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided4dInt32")
add_test(testZfpDecodeBlock4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock4dInt64")
add_test(testZfpDecodeBlockStrided4dInt64 "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided4dInt64")
add_test(testZfpDecodeBlock1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock1dFloat")
add_test(testZfpDecodeBlockStrided1dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided1dFloat")
add_test(testZfpDecodeBlock1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock1dDouble")
add_test(testZfpDecodeBlockStrided1dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided1dDouble")
add_test(testZfpDecodeBlock2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock2dFloat")
add_test(testZfpDecodeBlockStrided2dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided2dFloat")
add_test(testZfpDecodeBlock2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock2dDouble")
add_test(testZfpDecodeBlockStrided2dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided2dDouble")
add_test(testZfpDecodeBlock3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock3dFloat")
add_test(testZfpDecodeBlockStrided3dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided3dFloat")
add_test(testZfpDecodeBlock3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock3dDouble")
add_test(testZfpDecodeBlockStrided3dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided3dDouble")
add_test(testZfpDecodeBlock4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock4dFloat")
add_test(testZfpDecodeBlockStrided4dFloat "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided4dFloat")
add_test(testZfpDecodeBlock4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlock4dDouble")
add_test(testZfpDecodeBlockStrided4dDouble "/home/cc/local_build/zfp/build_debug/bin/testZfpDecodeBlockStrided4dDouble")
